### ISSUE TITLE
provide a way to match a sub-menu entry to a menu-entry

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/vicav-app-api#13]
when selecting a map-type via submenu-item, we need a way to match this map type to on opened via the main menu.

easiest way would be to re-use the menu-item-ids for corresponding submenu-item ids.

**Comment by simar0at** [comment]
I think the value of `target` is already used to reference a particular piece of content in other projects so I will provide this as identifier for a window to open or bring to front.
