### ISSUE TITLE
no need to escape slashes in projectconfig json response

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/vicav-app-api#15]
currently, the `logo.img` and `icon` urls in the `/vicav/project` json response have their slashes escaped, which is not necessary. see:

![Screenshot_20231002_101511](https://github.com/acdh-oeaw/vicav-app-api/assets/20753323/b33604b2-2cf7-4eb3-9fb2-bf1724a60f98)

**Comment by simar0at** [comment]
This is an automatic feature and hard to change. If it does not cause problems I will not do anything about it.
