### ISSUE TITLE
Include necessary data attributes in bibliography links

### ISSUE THREAD

**Issue by ttechnicus** [acdh-oeaw/vicav-app-api#18]
We need the parameter data-target-type="bibliography-query" and data-text-id in the element dataset for the bibliography links, and the marker data.

As of now, the output has data-target-type="External-link": https://vicav.acdh-ch-dev.oeaw.ac.at/vicav/text?id=vicavExplanationBibliography

The marker data is also missing these data: https://vicav.acdh-ch-dev.oeaw.ac.at/vicav/bibl_markers_tei?query=.*&scope=geo

**Comment by simar0at** [comment]
Added an implementation in [vicav-app 35778285](https://github.com/acdh-oeaw/vicav-app/commit/35778285)
Please review and comment.

**Comment by ttechnicus** [comment]
@simar0at Instead of 'Bibl' could we go with a more telling name for the ItemType? For example 'BiblioTei' (after the endpoint it gets its data from), or 'BiblioEntries'?

I would also like to extend the task, and kindly ask you to add this to the componentNames of the ItemType in the Api definition.

**Comment by simar0at** [comment]
The `data-target-type` is meant to convey the window type in my opinion. I thought about renaming it `data-component-name`.  
For map markers for example there now is a `data-endpoint` but the `data-target-type` is `WMap`.  
If you already have the name of the component for bibliographic queries and displaying the results then I would return that.

**Comment by ttechnicus** [comment]
I would prefer the text component to be called `BiblioEntries`, but this is open to discussion.

As per the name of the data attribute, that should perhaps go into a new task. For me `data-target-type` seems more semantic, while `data-component-name` refers to the implementation which is less preferable IMHO. If you wish, we could address Christoph with this idea and create a new task for it if he agrees.

**Comment by simar0at** [comment]
Let's standardize on `data-target-type` and `targetType` and we use `BiblioEntries` as the component name for a combined query and list view of bibliographic entries.

**Comment by ttechnicus** [comment]
@simar0at Let's get rid of the previous `BiblioQuery` target type in the menu, too. Please exchange this with `BiblioEntries`, and into the `target` field just put an empty string if you only want to display the search form.

**Comment by ttechnicus** [comment]
@simar0at  I changed the vicav example in the api definition file to illustrate what I mean. See https://github.com/acdh-oeaw/vicav-app-api/commit/82d1d9cf125699dbe7a6666dc017151a0d00c7c9

**Comment by simar0at** [comment]
I think this part is finished and works.
