### ISSUE TITLE
provide map base tilelayer url via `/vicav/project`

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/vicav-app-api#5]
currently, the project config endpoint provides the initial map view state (center, zoom), but expects the client to configure the base tile layer url from somewhere else.

it would be cool if the api could provide a base tilelayer `url` and `attribution` as part of the project config.

**Comment by simar0at** [comment]
The map provider (currently mapbox) is largely independent of the coordinates we want to show. It should be easy to update this URL as long as it uses the same API.  
For this reason we will keep the coordinates and zoom level separated from the actual map service.  
We should add the attribution also as a build time environment variable and manage both using GitHub environments.
