### ISSUE TITLE
clarify format for array query params like `scope`

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/vicav-app-api#6]
the project config endpoint returns a `query` object for map markers, which includes a `scope` array, e.g. `["geo", "reg"]`.

however, it is unclear in which format this array should be provided back to the `bibl_markers_tei` endpoint, which expects a string value for `scope`

**Comment by simar0at** [comment]
The `bibl_markers_tei` endpoint now accepts an array of scope. All enum values can be used but geo_reg does not make much 
sense.  
Example: https://vicav.acdh-ch-dev.oeaw.ac.at//vicav/bibl_markers_tei?query=Ma.*&scope=geo&scope=reg
