### ISSUE TITLE
clarify json return type of `{name}_markers` endpoints

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/vicav-app-api#8]
currently, only the `application/xml` return type is specified (as "string")

**Comment by simar0at** [comment]
`application/xml` is only for the legacy UI and any concrete description of the returned XML would be a waste of time. What do you suggesst we use here? Maybe just remove any mention of `application/xml`?

**Comment by stefanprobst** [comment]
personally i only care about a schema for the `application/json` response, similar to what `/vicav/bibl_markers_tei` has (see [here](https://github.com/acdh-oeaw/vicav-app-api/blob/master/openapi.json#L1078-L1084))

**Comment by simar0at** [comment]
Clarified as same as `/vicav/bibl_markers_tei`.
